# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparseSLOPE <- function(x, y, control) {
    .Call(`_SLOPE_sparseSLOPE`, x, y, control)
}

denseSLOPE <- function(x, y, control) {
    .Call(`_SLOPE_denseSLOPE`, x, y, control)
}

sortedL1ProxCpp <- function(x, lambda, method) {
    .Call(`_SLOPE_sortedL1ProxCpp`, x, lambda, method)
}

