# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SLOBE_ADMM_approx_missing <- function(beta_start, x_miss, x_init, y, a_prior, b_prior, covmat, sigma = 1.0, fdr = 0.05, tol = 1e-04, known_sigma = FALSE, max_iter = 100L, verbose = FALSE, bh = TRUE, known_cov = FALSE) {
    .Call(`_SLOPE_SLOBE_ADMM_approx_missing`, beta_start, x_miss, x_init, y, a_prior, b_prior, covmat, sigma, fdr, tol, known_sigma, max_iter, verbose, bh, known_cov)
}

lambdaSequence <- function(n_lambda, q, theta1, theta2, lambda_type, n) {
    .Call(`_SLOPE_lambdaSequence`, n_lambda, q, theta1, theta2, lambda_type, n)
}

sortedL1ProxCpp <- function(x, lambda, method) {
    .Call(`_SLOPE_sortedL1ProxCpp`, x, lambda, method)
}

sparseSLOPE <- function(x, y, control) {
    .Call(`_SLOPE_sparseSLOPE`, x, y, control)
}

denseSLOPE <- function(x, y, control) {
    .Call(`_SLOPE_denseSLOPE`, x, y, control)
}

