# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sortedL1ProxCpp <- function(x, lambda) {
    .Call(`_SLOPE_sortedL1ProxCpp`, x, lambda)
}

lambdaSequenceCpp <- function(n_lambda, q, theta1, theta2, lambda_type, n) {
    .Call(`_SLOPE_lambdaSequenceCpp`, n_lambda, q, theta1, theta2, lambda_type, n)
}

cvSparseCpp <- function(x, y, cv_args, model_args) {
    .Call(`_SLOPE_cvSparseCpp`, x, y, cv_args, model_args)
}

cvDenseCpp <- function(x, y, cv_args, model_args) {
    .Call(`_SLOPE_cvDenseCpp`, x, y, cv_args, model_args)
}

sparseSLOPE <- function(x, y, control) {
    .Call(`_SLOPE_sparseSLOPE`, x, y, control)
}

denseSLOPE <- function(x, y, control) {
    .Call(`_SLOPE_denseSLOPE`, x, y, control)
}

bigSLOPE <- function(x, y, control) {
    .Call(`_SLOPE_bigSLOPE`, x, y, control)
}

